#  Altered: 2024/12/26 - 12:26
#  Updated: ter 17 fev 2026 16:06:14 -04
#
#  Copyright (c) 2024-2025, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
name: "Build rootfs VoidBR"
description: "Builds a tarball rootfs image for VoidBR"

inputs:
  name:
    description: "Name for the ISO"
    required: true
  tmate:
    description: "Enable debugging with tmate"
    required: false
    default: false
  github_token:
    description: "GitHub token for authentication"
    required: true
  message_thread_id:
    description: "Telegram message thread id"
    required: false

outputs:
  iso_path:
    description: "Path to the generated ISO file"
    value: ${{ steps.build.outputs.iso_path }}
  xz_path:
    description: "Path to the generated TAR.XZ file"
    value: ${{ steps.build.outputs.xz_path }}
  release_name:
    description: "Name of the release"
    value: ${{ steps.prepare-iso.outputs.release_name }}

runs:
  using: "composite"
  steps:
    - name: Definir a função send_telegram_message no script temporário
      shell: bash
      env:
        TELEGRAM_TOKEN: "${{ inputs.telegram_token }}"
        TELEGRAM_CHAT_ID: "${{ inputs.telegram_chat_id }}"
        TELEGRAM_MESSAGE_THREAD_ID: "${{ inputs.telegram_message_thread_id }}"
      run: |
        #Definir a função send_telegram_message no script temporário
        cat << 'EOF' > /tmp/send_telegram_message.sh
        export TERM=${TERM:-xterm}
        export TERM=${TERM:-xterm-256color}
        ...
        export -f send_telegram_message
        EOF

    - name: Display the current user in CONTAINER
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        replicate "#"
        msg_raw "Current host is     : $(hostname)"
        msg_raw "Current user is     : $(whoami)"
        msg_raw "Current user ID is  : $(id -u)"
        msg_raw "Current user details: $(id)"
        replicate "#"
        df -hT || true
        replicate "#"
        ls -la /mnt || true
        replicate "#"

    - name: Setup build environment
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        {
        echo 'repository=https://void.voidbr.org/voidlinux/current'
        echo 'repository=https://void.voidbr.org/voidlinux/extra'
        echo 'repository=https://void.voidbr.org/voidlinux/current/nonfree'
        echo 'repository=https://void.voidbr.org/voidlinux/current/multilib'
        echo 'repository=https://void.voidbr.org/voidlinux/current/multilib/nonfree'
        echo
        echo 'repository=https://void.chililinux.com/voidlinux/current'
        echo
        echo 'repository=https://repo-fastly.voidlinux.org/current'
        echo 'repository=https://repo-fastly.voidlinux.org/current/nonfree'
        echo 'repository=https://repo-fastly.voidlinux.org/current/multilib'
        echo 'repository=https://repo-fastly.voidlinux.org/current/multilib/nonfree'
        } >> /etc/xbps.d/00-repository-main.conf

        xbps-install -Sy -f tree duf > /dev/null

    - name: Garantir REPO_NAME
      shell: bash
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_ENV"

    - name: Configurar o ambiente
      shell: bash
      run: |
        WORK_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}"
        PROFILE_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}/chili-void-mklive"
        echo "WORK_PATH=$WORK_PATH" >> "$GITHUB_ENV"
        echo "PROFILE_PATH=$PROFILE_PATH" >> "$GITHUB_ENV"

    - name: Checkout chili-void-mklive
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        REPO="https://github.com/chililinux/chili-void-mklive"
        msg_raw "Repository: $REPO"
        rm -rf "$PROFILE_PATH" || true
        if ! git clone --depth 1 "$REPO" "$PROFILE_PATH"; then
          echo "Falha ao clonar o repositorio $REPO em $PROFILE_PATH"
          exit 1
        fi
        git config --global --add safe.directory "$PROFILE_PATH" || true
        rm -rf /__t/* || true

    - name: Setup TMATE Session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event.client_payload.tmate == true || inputs.tmate == true}}
      with:
        install-dependencies: false
        detached: true

    - name: Build ROOTFS tarball
      shell: bash
      env:
        DEBUG: ${{ inputs.tmate }}
        DISTRONAME: ${{ inputs.name }}
        ...
        cleanup_and_move_files

    - name: Extrair data do nome do arquivo .tar.xz e definir tag_name
      id: set-tag-name
      shell: bash
      run: |
        FILENAME="$XZ_BASENAME"
        TAG_NAME=$(echo "$FILENAME" | grep -oP '\d{8}')-$(date +%H%M)
        echo "XZ_TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Set ISO path
      shell: bash
      run: |
        echo "iso_path=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_OUTPUT"
        echo "xz_path=$WORK_PATH/$XZ_BASENAME" >> "$GITHUB_OUTPUT"
