#  Altered: 2024/12/26 - 12:26
#  Updated: ter 17 fev 2026 20:12:31 -04
#
#  Copyright (c) 2024-2026, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
name: "Build rootfs VoidBR"
description: "Builds a tarball rootfs image for VoidBR"

inputs:
  name:
    description: "Name for the ISO"
    required: true
  tmate:
    description: "Enable debugging with tmate"
    required: false
    default: false
  github_token:
    description: "GitHub token for authentication"
    required: true
  message_thread_id:
    description: "Telegram message thread id"
    required: false
  message_thread_id_rootfs:
    description: "Telegram message thread id rootfs"
    required: false

outputs:
  iso_path:
    description: "Path to the generated ISO file"
    value: ${{ steps.build.outputs.iso_path }}
  xz_path:
    description: "Path to the generated TAR.XZ file"
    value: ${{ steps.build.outputs.xz_path }}
  release_name:
    description: "Name of the release"
    value: ${{ steps.prepare-iso.outputs.release_name }}

runs:
  using: "composite"
  steps:
    - name: Display the current user in CONTAINER
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        msg "- name: Display the current user in CONTAINER"
        replicate "#"
        msg_raw "Current host is     : $(hostname)"
        msg_raw "Current user is     : $(whoami)"
        msg_raw "Current user ID is  : $(id -u)"
        msg_raw "Current user details: $(id)"
        msg_raw "Current path        : $(pwd)"
        replicate "#"
        duf -all || true
        replicate "#"
        df -hT || true
        replicate "#"
        ls -la /mnt || true
        replicate "#"

    - name: Install Required Packages and Libraries no CONTAINER
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        replicate
        msg "- name: Install Required Packages and Libraries no CONTAINER"
        {
          echo 'repository=https://void.voidbr.org/voidlinux/current'
          echo 'repository=https://void.voidbr.org/voidlinux/extra'
          echo 'repository=https://void.voidbr.org/voidlinux/current/nonfree'
          echo 'repository=https://void.voidbr.org/voidlinux/current/multilib'
          echo
          echo 'repository=https://void.voidbr.org/voidlinux/current/multilib/nonfree'
          echo 'repository=https://repo-fastly.voidlinux.org/current'
          echo 'repository=https://repo-fastly.voidlinux.org/current/nonfree'
          echo 'repository=https://repo-fastly.voidlinux.org/current/multilib'
          echo 'repository=https://repo-fastly.voidlinux.org/current/multilib/nonfree'
          echo
          echo 'repository=https://void.chililinux.com/voidlinux/current'
          echo
          } > /etc/xbps.d/00-repository-main.conf

          xbps-install -Syu
          xbps-install -yu xbps
          xbps-install -yu \
            bash \
            xtools \
            sudo \
            openssh \
            tmate \
            xz \
            zip \
            p7zip \
            jq \
            github-cli \
            kmod \
            which \
            vpm \
            libstdc++ \
            nano \
            curl \
            git \
            bash \
            tree \
            duf \
            gettext \
            rsync \
            util-linux \
            coreutils \
            sed \
            grep \
            btrfs-progs \
            e2fsprogs \
            exfatprogs \
            dosfstools \
            xfsprogs
          vinstall -Scc
          xbps-install -Syu ncurses
          replicate

    - name: Definir REPO_NAME
      shell: bash
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_ENV"

    - name: Configurar o ambiente
      shell: bash
      run: |
        WORK_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}"
        PROFILE_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}/chili-void-mklive"
        echo "WORK_PATH=$WORK_PATH"       >> "$GITHUB_ENV"
        echo "PROFILE_PATH=$PROFILE_PATH" >> "$GITHUB_ENV"

    - name: Checkout chili-void-mklive
      shell: bash
      run: |
        #Checkout chili-void-mklive
        source /tmp/send_telegram_message.sh
        REPO="https://github.com/chililinux/chili-void-mklive"
        msg_raw "Repository: $REPO"

        rm -rf "$PROFILE_PATH" || true
        if ! git clone --depth 1 "$REPO" "$PROFILE_PATH"; then
          echo "Falha ao clonar o repositorio $REPO em $PROFILE_PATH"
          exit 1
        fi
        # ativando 'git config --global --add safe.directory'
        git config --global --add safe.directory "$PROFILE_PATH" || true

        # clean '/__t/' directory
        rm -rf /__t/* || true

    - name: Setup TMATE Session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event.client_payload.tmate == true || inputs.tmate == true}}
      with:
        install-dependencies: false
        detached: true

    - name: Build ROOTFS tarball
      shell: bash
      env:
        DEBUG: ${{ inputs.tmate }}
        DISTRONAME: ${{ inputs.name }}
        EDITION: ${{ inputs.edition }}
        MANJAROBRANCH: ${{ inputs.manjaro_branch }}
        COMMUNITYBRANCH: ${{ inputs.community_branch }}
        BIGBRANCH: ${{ inputs.biglinux_branch }}
        SCOPE: ${{ inputs.scope }}
        KERNEL: ${{ inputs.kernel }}
        OFFICE: ${{ inputs.office-chooser }}
        RELEASE_TAG: ${{ inputs.release_tag }}
      run: |
        # BUILD ISO Image
        # Denine path for directory

        source /tmp/send_telegram_message.sh

        # Check if iso-profiles directory exists before proceeding
        if [[ ! -d "$PROFILE_PATH" ]]; then
          die "ERRO(L427): Diret처rio $PROFILE_PATH n찾o localizado!"
        fi

        # listando diret처rio iso-profiles no diret처rio atual
        msg_run "ls -lah $WORK_PATH"

        build_mkroot_fs() {
          replicate "######################### RESUMO #################################" 1
          msg_raw "BUILD COMMAND            : ./mkrootfs --automatic -v"
          msg_raw "PROFILE_PATH             : $PROFILE_PATH"
          replicate "#"
          msg_raw "WORK_PATH                : $WORK_PATH"
          msg_raw "PROFILE_PATH             : $PROFILE_PATH"
          msg_raw "ISO profiles path        : $PROFILE_PATH/$EDITION"
          #replicate "#"
          #msg_raw "ROOT_RUN_DIR             : $(< /root/.config/manjaro-tools/iso-profiles.conf)"
          #msg_raw "BUILDUSER_RUN_DIR        : $(< /home/builduser/.config/manjaro-tools/iso-profiles.conf)"
          replicate "#"

          pushd "$PROFILE_PATH" > /dev/null || true
          [[ ${{ inputs.tmate }} == 'true' ]] && ./mkrootfs --automatic -v || ./mkrootfs --automatic -v > /dev/null
          popd > /dev/null
        }

        cleanup_and_move_files() {
          OUTPUT_ISO_PATH_NAME=$(find "$PROFILE_PATH" -type f -name "*.iso" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
          OUTPUT_XZ_PATH_NAME=$(find "$PROFILE_PATH" -type f -name "*.tar.xz" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
          ISO_BASENAME=$(basename "$OUTPUT_ISO_PATH_NAME")
          XZ_BASENAME=$(basename "$OUTPUT_XZ_PATH_NAME")

          echo "OUTPUT_ISO_PATH_NAME=$OUTPUT_ISO_PATH_NAME" >> "$GITHUB_ENV"  # Exporta OUTPUT_ISO_PATH_NAME para outras etapas
          echo "OUTPUT_XZ_PATH_NAME=$OUTPUT_XZ_PATH_NAME" >> "$GITHUB_ENV"    # Exporta OUTPUT_ISO_PATH_NAME para outras etapas
          echo "ISO_BASENAME=$ISO_BASENAME" >> "$GITHUB_ENV"                  # Exporta OUTPUT_ISO_PATH_NAME para outras etapas
          echo "XZ_BASENAME=$XZ_BASENAME" >> "$GITHUB_ENV"                    # Exporta OUTPUT_ISO_PATH_NAME para outras etapas

          if [[ -n "$OUTPUT_ISO_PATH_NAME" ]]; then
            mv -fv "$OUTPUT_ISO_PATH_NAME" "$WORK_PATH/" || echo "ERRO: Falha ao mover arquivo ISO $OUTPUT_ISO_PATH_NAME"
            echo "ISO_FULLNAME=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_ENV"
          fi
          if [[ -n "$OUTPUT_XZ_PATH_NAME"  ]]; then
            mv -fv "$OUTPUT_XZ_PATH_NAME" "$WORK_PATH/"  || echo "ERRO: Falha ao mover arquivo XZ $OUTPUT_XZ_PATH_NAME"
            echo "XZ_FULLNAME=$WORK_PATH/$XZ_BASENAME" >> "$GITHUB_ENV"
          fi
        }

        build_mkroot_fs
        cleanup_and_move_files

    - name: Extrair data do nome do arquivo .tar.xz e definir tag_name
      id: set-tag-name
      shell: bash
      run: |
        FILENAME="$XZ_BASENAME"
        TAG_NAME=$(echo "$FILENAME" | grep -oP '\d{8}')-$(date +%H%M)
        echo "XZ_TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Set ISO path
      shell: bash
      run: |
        # Set outputs
        echo "iso_path=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_OUTPUT"
        echo "xz_path=$WORK_PATH/$XZ_BASENAME" >> "$GITHUB_OUTPUT"
